name: "Get CI"

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - '*'

jobs:
  macos-run-tests:
    name: Unit Tests (Xcode ${{ matrix.xcode }})
    strategy:
      fail-fast: false
      matrix:
        xcode: ["14.3", "15.0", "15.3"]
        include:
          - xcode: "15.3"
            macos: macOS-14
          - xcode: "15.0"
            macos: macOS-14
          - xcode: "14.3"
            macos: macOS-13
    runs-on: ${{ matrix.macos }}
    env:
      DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: swift test

  linux-run-tests:
    name: Unit Tests (Linux, Swift ${{ matrix.swift }})
    strategy:
      fail-fast: false
      matrix:
        swift: ["5.9"]
    runs-on: ubuntu-latest
    container: swift:${{ matrix.swift }}
    steps:
      - uses: actions/checkout@v2
      - name: Run Tests
        run: swift test
